### ISSUE TITLE
`enhanceSelectElement` does not unset `name` as claimed in README

### ISSUE THREAD

**Issue by lennym** [alphagov/accessible-autocomplete#130]
The README section for `enhanceSelectElement` states the following:

> Default the autocomplete name attribute to '' to prevent it being included in form submissions

However the code at https://github.com/alphagov/accessible-autocomplete/blob/master/src/wrapper.js#L36 sets it to the same name as the select element unless explicitly overwritten - and it cannot be explicitly set to `''` since that is a falsy value (as per #128)

I'm not sure whether the docs or the code are correct in this instance (though my instinct is the code) so haven't PR'ed a fix.

**Comment by tvararu** [comment]
Actually, the name should stay blank (for the reason stated). That's a bug with the code, [introduced here](https://github.com/alphagov/accessible-autocomplete/commit/82f511906f52949f66def8304ae64ca3a08aafd5) (we didn't notice), the docs are correct.

Feel free to fix! (updating tests to reflect behaviour)

**Comment by lennym** [comment]
It won't be today (I was meant to be heading home an hour ago!) but I'll see if I can find time next week.
