### ISSUE TITLE
v1.0.4 not built before publish

### ISSUE THREAD

**Issue by lennym** [alphagov/accessible-autocomplete#135]
I think this one is 100% my bad, but I think the compiled code in v1.0.4 doesn't match the build output from the source. It's possible/probably that I forgot to build or forgot to add the built code before raising my PR. Running the npm version gives different results to when I have a local version `npm link`ed into my project.

Normally I'd suggest protecting against this by compiling in pre-publish hook for npm, but that doesn't solve the fact that some use cases will want the compiled code in github. Given that, I'm working on a pre-commit hook that will keep things synced.

Meanwhile, you might want to rebuild and publish a new version.

Sorry!

**Comment by tvararu** [comment]
Just published `v1.0.5` to address this!

Don't apologise. If anything it's my fault and I'm surprised how I've managed to avoid bumping into this before.

> but that doesn't solve the fact that some use cases will want the compiled code in github.

Yes, chiefly our GitHub pages.
