### ISSUE TITLE
input box is empty but sends first option line

### ISSUE THREAD

**Issue by maxf** [alphagov/accessible-autocomplete#143]
If you apply autocomplete to a standard select:
```html
<select>
  <option>first</option>
  <option>second</option>
  <option>third</option>
</select>
```
the text input box is empty. But upon submitting the form the first option is sent.

What should happen is that initially the text input box should show the text of the first option.

**Comment by tvararu** [comment]
@maxf can you update your issue with the the code / a link to an example? It's showing up as an empty code block for me.

If you modify the [form example](https://github.com/alphagov/accessible-autocomplete/blob/5a15f22aeaa9b7e232bd23bb198eab0fbff87240/examples/form.html#L334) to remove `selected` from the options, it will prefill the input with "Abu Dhabi", which is the first option, just as you describe.

**Comment by hannalaakso** [comment]
Hi @maxf

How did you get on with this? 

I've had a look and wasn't able to replicate the issue. 

If you use the `form.html` example to test this as Theo suggests, the autocomplete is prefilled with "Abu Dhabi" which is the first option.

If you still think this is an issue, would you be able to link to a code example of where this is happening.

Thanks 🙂 

Hanna

**Comment by maxf** [comment]
wow, that was a while ago ;)
It's probably fixed and I didn't notice it.

**Comment by hannalaakso** [comment]
Thanks @maxf! 🙂
