### ISSUE TITLE
Clarify support for <div>

### ISSUE THREAD

**Issue by maxf** [alphagov/accessible-autocomplete#144]
Using `<div id='location-picker' name='location'></div>` is an alternative to `<select ...>` which adds the possibility of entering values that aren't in the autocomplete list. 

It would be nice to have it mentioned in the documentation. It would be even nicer if instead of a div you could use `<input type="text" name="location"/>`, which would make it possible to do progressive enhancement, like with select

**Comment by tvararu** [comment]
Thanks @maxf!

I agree this needs some better documentation, showing the HTML needed for the basic usage.

The second part, about enhancing an `<input>` in place, isn't trivial I'm afraid. I wrote a bit about it here: https://github.com/alphagov/accessible-autocomplete/issues/95#issuecomment-300466988
