### ISSUE TITLE
& (ampersand) in option becomes &amp; in the text input

### ISSUE THREAD

**Issue by joelanman** [alphagov/accessible-autocomplete#151]
To recreate:

enhance a select with an ampersand in an option:
```
<select>
    <option value="?organisations=hm-revenue-customs">HM Revenue & Customs (83389)</option>
</select>
```

When this is selected using the autocomplete it becomes &amp; in the text input

![image](https://cloud.githubusercontent.com/assets/1132904/26596574/2254ff12-4567-11e7-908f-c4883c2e8c0f.png)

This happens whether the ampersand is escaped in the <option> (&amp;) or not

**Comment by tvararu** [comment]
Interesting, thanks for reporting!

**Comment by dracos** [comment]
You also can't search including the `&` and the word after it unless you enter `&amp;`.

**Comment by dracos** [comment]
PR at #182 that hopefully fixes that plus the original bug.
