### ISSUE TITLE
enhanceSelectElement always sets autoselect to true

### ISSUE THREAD

**Issue by joelanman** [alphagov/accessible-autocomplete#163]
`opts.autoselect = opts.autoselect || true`

should be 

`if (opts.autoselect === undefined) opts.autoselect = true`

I think

**Comment by tvararu** [comment]
Yep, good catch!

**Comment by joelanman** [comment]
just looking into this - why are we setting autoselect to true in `enhanceSelectElement`?

**Comment by tvararu** [comment]
@joelanman it makes it more similar to a real `<select>` in that it doesn't allow you to get away as easily without picking an option.

**Comment by joelanman** [comment]
not sure about that - most selects would have '-choose an option-' first value. Also this means you get different behaviour just because you're enhancing a select - thats a bit unexpected.

**Comment by tvararu** [comment]
That's a fair point and I do agree with it, @edwardhorsford may remember the exact reasoning (we were also considering making `autocomplete: true` the real default at one point)

**Comment by edwardhorsford** [comment]
Reasoning:

We're setting the default to the most sensible option in each case. For enhanced inputs we need users to be able to type anything, and not have to pick from the list. For selects, users *must* pick from the list. So the most sensible option is different for each.

The challenge here is to have consistent options, but also an easy way for us to provide 'recommended' sets of options. So far we've done this by having defaults that offer our recommended options.

My concern with changing this default is that we'll see most users of this component not using autoselect- a feature we've found to be very beneficial. I'm very open to alternate suggestions that achieve this though, and agree the inconsistency is awkward.

**Comment by joelanman** [comment]
this was fixed by #167
