### ISSUE TITLE
npm run dev is failing with npm install, working with yarn

### ISSUE THREAD

**Issue by joelanman** [alphagov/accessible-autocomplete#172]
Sorry this is a pretty vague issue.

To recreate:

1. Clone from scratch
2. npm install
3. npm run dev

Instead of running normally, it opens at `http://localhost:8080/undefined`, and none of the assets (css, js) load, instead they 404.

If I use yarn instead for step 2 above, everything works fine, so I imagine this is an issue with a package that has been updated.

My node version is 6.10.3, npm is 5.0.3

**Comment by tvararu** [comment]
I'm looking into this, thanks for reporting!

**Comment by tvararu** [comment]
I've tracked this down to be due to a transitive dependency on `webpack-dev-middleware@^1.0.11` from `karma-webpack@^2.0.1`.

This issue is reproducible with `yarn` by updating `yarn.lock` as such:

```diff
 webpack-dev-middleware@^1.0.11, webpack-dev-middleware@^1.10.2:
-  version "1.10.2"
-  resolved "https://registry.yarnpkg.com/webpack-dev-middleware/-/webpack-dev-middleware-1.10.2.tgz#2e252ce1dfb020dbda1ccb37df26f30ab014dbd1"
+  version "1.11.0"
+  resolved "https://registry.yarnpkg.com/webpack-dev-middleware/-/webpack-dev-middleware-1.11.0.tgz#09691d0973a30ad1f82ac73a12e2087f0a4754f9"
   dependencies:
     memory-fs "~0.4.1"
     mime "^1.3.4"
```

Not sure how this exactly is causing the normal `dev` task to fail but I'm still investigating.
