### ISSUE TITLE
Scrolling list on touch device selects first item touched

### ISSUE THREAD

**Issue by dashouse** [alphagov/accessible-autocomplete#177]
Look at https://accessible-autocomplete-pr-176.herokuapp.com/examples/ **on a mobile or touch device**

**Steps to recreate bug**
1. Pick any of the autocomplete examples and type "a"
2. Scroll this list, noting the country that you touched to start the scroll
3. As you reach the end of the scrollable area, let go

**Actual Result:**
The country that you touched to begin the scroll will be selected

**Expected result:**
 I would be able to carry on scrolling until the end of the list

**Impact**
- Users will be unable to select the correct item from the list
- Once an item is selected it's hard for a user to understand how to see the list again (they need to delete the current selection using backspace) 
- The `{ showAllValues: true }` option will be unusable on a touch device as scrolling is the only way to interact with it

Only tested on iOS Safari but I would imagine Android Chrome would have the same problem

**Comment by joelanman** [comment]
Have tested and the same issue exists on android

**Comment by tvararu** [comment]
I'm 90% sure this bug was introduced with this change: https://github.com/alphagov/accessible-autocomplete/pull/85

**Comment by hannalaakso** [comment]
The PR app in the description is no longer available so I tested this on the [master github app](https://alphagov.github.io/accessible-autocomplete/examples/) on iPhone 5s OS 11.2.1. I believe this is fixed as I am able to:
- Carry on scrolling until the end of the list
- Select the correct item from the list
- Use the `{ showAllValues: true }` option

As you touch the items on the list it looks like they get the selected state which is captured by https://github.com/alphagov/accessible-autocomplete/issues/74

The third issue flagged in the description is not fixed and is captured in this issue: https://github.com/alphagov/accessible-autocomplete/issues/166
> Once an item is selected it's hard for a user to understand how to see the list again (they need to delete the current selection using backspace)

**Comment by dashouse** [comment]
@hannalaakso looks fixed, yep
