### ISSUE TITLE
If you type, then press down, then type, your first char doesn't appear

### ISSUE THREAD

**Issue by joelanman** [alphagov/accessible-autocomplete#179]
1. Start typing, eg 'ge'
2. Press down, this highlights an option in the list
3. Continue typing 'rm'

Expected: 'germ' is now in the input
Actual result: 'gem' is now in the input

The first character in step 3 seems to just return focus to the input, it doesn't enter the actual character.

**Comment by tvararu** [comment]
Can confirm. Interesting, this used to work correctly in Chrome, and I was surprised that it did considering the way it's implemented. Will investigate why this is no longer the case, and potentially write an end-to-end test to prevent it from regressing again.

**Comment by tvararu** [comment]
We've published v1.3.2 which addresses this issue for the default version of the autocomplete and all browsers.

It's still present in the React version on IE9, IE10, and IE11.
