### ISSUE TITLE
Starting off progressive select with nothing shown in text box

### ISSUE THREAD

**Issue by dracos** [alphagov/accessible-autocomplete#181]
Is it possible to enhance a `select` and not have the first option shown in the text box? I don't really want to have a blank option at the top, but that seems to be the only way unless I'm missing something (certainly possible!). I've tried calling `enhanceSelectElement` with `defaultValue: ''` but that doesn't appear to change anything, the first option is still shown when the page is loaded.

**Comment by dracos** [comment]
Ah, so this is because in wrapper.js, the `if (opts.selectElement.value || opts.defaultValue === undefined)` passes because the `opts.selectElement.value` will already be equal to the first entry of the select, regardless of `defaultValue` being overridden. So it looks like it will have to have a blank option (but it can have content, matching the label, I guess).

**Comment by joelanman** [comment]
I think if you set `autoselect` false you should get what you need. I think this is another example of it being unexpected and confusing that autoselect is on by default only in the progressive enhancement approach.

**Comment by dracos** [comment]
No, it makes no difference whether `autoselect` is true or false.

**Comment by joelanman** [comment]
ah sorry yeh, I think this is by design, in the sense that if the original `select` couldn't be submitted blank, the enhanced autocomplete can't either. I think the workaround of an initial blank value is probably correct as that's how you'd achieve this experience with a default `select`.

**Comment by tvararu** [comment]
Hello! 👋 

I might be misunderstanding the issue here, but I think what you need is solved by using a [null option](https://github.com/alphagov/accessible-autocomplete#null-options).

Will close for now, but please reopen if that's the case!
