### ISSUE TITLE
IE10 - using arrows to navigate list selects item by mistake

### ISSUE THREAD

**Issue by adamliptrot-oc** [alphagov/accessible-autocomplete#193]
Using IE10 (checked on Win 7 and Win 8) when typing in a country (eg Fr) and then using the down arrow key to navigate the list. 
When the key is pressed after the highlight is on the first item in the list, the second item in the list is automatically selected.

![arrow key ie10](https://user-images.githubusercontent.com/14074579/28267731-48b9a2a0-6af3-11e7-972e-7428d68fd486.gif)

**Comment by tvararu** [comment]
Thanks for the report @adamliptrot-oc! I can confirm this is a bug.
