### ISSUE TITLE
iOS Voiceover - status does not update when selection made

### ISSUE THREAD

**Issue by adamliptrot-oc** [alphagov/accessible-autocomplete#201]
When the user makes a selection, the status is not updated to indicate their selection.

1. User types in country eg 'Fr'
2. List appears, status says '29 results are available'
3. User selects from list eg France
4. Input updates to show the selection
5. Status announces '29 results are available'

The status should indicate a selection has been made eg 'France selected'. At the moment it doesn't inform the user what is happening.

**Comment by tvararu** [comment]
The status region isn't updated when a user selects an option. Rather, selection is accompanied by a browser `.focus` change, which on a `role="option"` element will reliably cause every tested screen reader to announce the selected option.

From what you describe it sounds like you're experiencing a situation in which you've selected an option and the autocomplete reannounces that "29 results are available." I've just tested this on VoiceOver and indeed it seems to occur now whereas it didn't before, so this is a recent regression. Thanks for the report!

**Comment by bennpearson** [comment]
Changing `role="status"` to `role="alert"` and removing `aria-live="polite"` could fix this issue.

This from [mozilla.org](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions):
"To maximize compatibility, some people recommend adding a redundant aria-live="assertive" when using this role. However, adding both aria-live and role=alert causes double speaking issues in VoiceOver on iOS."

**Comment by hannalaakso** [comment]
Hi Adam,

Thanks for flagging this up and apologies for taking so long to reply.

It looks like more recent versions of iOS contain accessibility improvements that have fixed the issue which is good. The bug exists in iOS 10.3.3 (iPad/Safari). On iOS 11.2.1 (iPhone/Safari & Chrome) and 11.3.1 (iPad/Safari) when you select an item, VoiceOver says: "Select your country, text field, is editing, **France selected**, character mode, 6 results are available". 

Would you know what version of iOS you saw the bug on? Are you able to replicate it on the [demo page](https://alphagov.github.io/accessible-autocomplete/examples/)?

Thanks,
Hanna
