### ISSUE TITLE
custom results with html

### ISSUE THREAD

**Issue by jojo05** [alphagov/accessible-autocomplete#204]
Is there a way to include an external link in the custom result so that clicking on that link opens a new URL and otherwise selects the given option ?

**Comment by tvararu** [comment]
Hi @jojo05! Good question.

I think you could use the [`onConfirm`](https://github.com/alphagov/accessible-autocomplete#onconfirm-default---) option for this. You can call something like `window.open(url, '_blank')` as the callback to that function.

**Comment by jojo05** [comment]
Yes, this works but when you click you are already selecting an item

The pattern I was interested is providing a link in each item (say country name with a wikipedia link), so that you can optionally check the link if you're not sure about the option, but only making the selection if clicking outside the link.

**Comment by tvararu** [comment]
@jojo05 interesting. That's not something we support today, due to the way click events have to be implemented on the options for them to work correctly cross-device and cross-assistive technology.

I will keep this issue open as a feature request.

**Comment by jojo05** [comment]
Ok

A related question: 
How can customize the custom html so that the custom items display like a table (i.e. multiple consecutive spans of fixed width) ?

**Comment by tvararu** [comment]
@jojo05 you can try the `templates.suggestion` option https://github.com/alphagov/accessible-autocomplete#templates-default-undefined

But it may not be sufficient, depending on how complex is what you're trying to do. Let me know. 👌

**Comment by jojo05** [comment]
I am using span tags with style=width:200px but the width is ignored.

**Comment by jojo05** [comment]
CSS issue fixed by adding display:inline-block (also moved the CSS outside of JSX).
