### ISSUE TITLE
Extra commas when "No Search Results"

### ISSUE THREAD

**Issue by shaunbent** [alphagov/accessible-autocomplete#207]
Firstly, awesome work on this. Great example and loads to be learnt from this. I am just about to implement a very similar feature so going to take loads from this.

One thing I have spotted is that when there are no results there are two additional commas announced:

![autocomplete](https://user-images.githubusercontent.com/608566/28564581-55f2b554-7121-11e7-9720-c0774538697c.png)

**Comment by tvararu** [comment]
Thanks for the report @shaunbent!

Yeah, you've found one of the hacks that should be documented really. I've written an explanation here: https://github.com/alphagov/accessible-autocomplete/issues/200#issuecomment-316755847

I'd like to keep this issue open for discussion about alternative solutions to this. If you have any ideas, please pitch them 👍

**Comment by nickcolley** [comment]
Will be in the 2.0.0 release :)
