### ISSUE TITLE
publish version 1.6.1

### ISSUE THREAD

**Issue by revilossor** [alphagov/accessible-autocomplete#237]
Any ideas when a new version will be released / published? 

I'd like to submit a PR to [govuk-country-and-territory-autocomplete](https://github.com/alphagov/govuk-country-and-territory-autocomplete) that updates the version of this it uses - its on 1.4.1 ATM - there are a few changes / fixes we'd like to add to our service.

**Comment by revilossor** [comment]
@danmitchell- could you point me at someone who i could talk to about getting a new version of this published please?

**Comment by danmitchell-** [comment]
Hi @revilossor, apologies for the delay! I'm going to look to get https://github.com/alphagov/accessible-autocomplete/pull/214, https://github.com/alphagov/accessible-autocomplete/pull/233 and https://github.com/alphagov/accessible-autocomplete/pull/226 merged in this week and then I think we'll be able to publish a new version.

**Comment by danmitchell-** [comment]
Just #214 left to go and then we can publish a new release. Sorry for the delay

**Comment by danmitchell-** [comment]
v1.6.1 has been released @revilossor
