### ISSUE TITLE
`npm run dev` returns 404s for accessible-autocomplete

### ISSUE THREAD

**Issue by codekiln** [alphagov/accessible-autocomplete#253]
```
$ node -v
v9.5.0

$ npm -v
5.6.0
```

OS X 10.12.5

When I clone the repo, check out the tip of the master branch (64b07d76b), run `npm install` and `npm run dev`, I get 404s for accessible-autocomplete, and the examples are currently not working, with "Uncaught ReferenceError: accessibleAutocomplete is not defined" appearing in the console.

![dev tools network tab](https://user-images.githubusercontent.com/140930/36252748-9f06d3f4-1213-11e8-9396-1648116a331b.png)

![dev tools console](https://user-images.githubusercontent.com/140930/36252945-32668798-1214-11e8-8a33-40984b56f499.png)

**Comment by nickcolley** [comment]
Hey @codekiln :)

I think I know why this is broken, PR incoming.

Thanks for raising!
