### ISSUE TITLE
Result count incorrectly read with JAWS and NVDA on Chrome.

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/accessible-autocomplete#271]
Bug report via twitter:
["Hi, I tested the autocomplete withJAWS & NVDA on Chrome. For the results list it keep saying 1of58 even when I am on 5th result. It should say 5 of 58. It's a minor bug."](https://twitter.com/DigitalA11y/status/996981916598353920)

Note this isn't a browser / AT combo we recommend testing in. Creating the issue though so it's recorded.

**Comment by PRGfx** [comment]
This is because the option `tStatusSelectedOption` (or the `tSelectedOption` prop of Status) does not receive the currently selected index and returns `1 of __`. I think the autocomplete's state value `selected` should be available in the `Status` component as e.g. `selectedOptionIndex`.
