### ISSUE TITLE
Readability nit: Single letter variables

### ISSUE THREAD

**Issue by nickcolley** [alphagov/accessible-autocomplete#28]
When scanning the repo, there's a few variables that take a little bit to figure out what they do because of their names:

https://github.com/alphagov/accessible-typeahead/blob/enhance-select-element/src/typeahead.jsx#L4

https://github.com/alphagov/accessible-typeahead/blob/enhance-select-element/src/typeahead.jsx#L333

https://github.com/alphagov/accessible-typeahead/blob/enhance-select-element/src/typeahead.jsx#L228

https://github.com/alphagov/accessible-typeahead/blob/enhance-select-element/src/typeahead.jsx#L184

**Comment by tvararu** [comment]
I think `cn` for `classname`, `evt` for `event`, `idx` for `index` can be inferred from context? `kc` for `keyCodes` I agree should be changed.

**Comment by tvararu** [comment]
Reopening as @joelanman mentioned this same exact thing.

**Comment by joelanman** [comment]
it fits our style guide too - 'be descriptive with your naming' https://github.com/alphagov/styleguides/blob/master/js.md#naming-conventions
