### ISSUE TITLE
Spacebar input not registered when 'No results found'

### ISSUE THREAD

**Issue by AdenFraser** [alphagov/accessible-autocomplete#286]
When the autocomplete is configured with ``` { showAllValues: true }``` and a string is entered which does not create a match, but includes a space, the first spacebar key-press is not registered.

For example, take the use-case of an autocomplete/typeahead which allows users to also provide inputs which do not match the existing list of options — perhaps to store the users option against the list at a later point. 

When a user attempts to enter 'Petrograd and Leningrad' into the ``` { showAllValues: true }``` example:
![image](https://user-images.githubusercontent.com/1902819/43315232-3a0e65e4-918d-11e8-984b-08e9431a3bbc.png)

By the time they have entered `Pet` there are no results left:
![image](https://user-images.githubusercontent.com/1902819/43315247-44f07c7c-918d-11e8-8d1e-098a2e626365.png)

The user continues to type `rograd` without any problems: 
![image](https://user-images.githubusercontent.com/1902819/43315267-568483de-918d-11e8-8b9a-5c5eb9f7c1dd.png)

But should they continue to type `rograd and Leningrad` the following is registered:
![image](https://user-images.githubusercontent.com/1902819/43315299-6d6f8300-918d-11e8-9d2d-46aba7aa813e.png)

In order to overcome this issue, the user is forced to double hit space for each attempt to add a single space. The first space not being registered as it is used to open the option to show all values.

**Comment by 36degrees** [comment]
Hi Aden,

Thanks very much for raising a really comprehensive issue (and the PR!). I've been able to reproduce this bug using the steps you provided.

I'll take a look at your PR and see if we can get this fixed for you 👍
