### ISSUE TITLE
Bundle size increased from 7.3kb to 10.8kb in v1.6.2

### ISSUE THREAD

**Issue by tvararu** [alphagov/accessible-autocomplete#321]
This could be related to the dev dependencies being updated.

- 1.6.1: https://bundlephobia.com/result?p=accessible-autocomplete@1.6.1
- 1.6.2: https://bundlephobia.com/result?p=accessible-autocomplete@1.6.2

**Comment by dracos** [comment]
Hi, I saw this was closed as completed but it's still the case with the latest version, which is c. 11.5KB. If you remove the `useBuiltIns` from the babel config it drops to 8.3KB, but compiles to es5 fine as far as I and `es5-validator` can see. If you also remove the legacy IE plugins and the uglifyOptions, then it drops to just under 8KB. That's over 30% smaller. I don't understand what `useBuiltIns` is doing - all it seems to end up doing is adding additional unnecessary polyfills and a lot of webpack boilerplate.
