### ISSUE TITLE
Set result to Query rather than last selected option

### ISSUE THREAD

**Issue by brendyhenry90** [alphagov/accessible-autocomplete#327]
Using accessibleAutocomplete.enhanceSelectElement on a select element. If I choose a value from the dropdown eg Honda, then delete the field and enter something not an option eg blah blah from the select element. The value sent on submission is the last selected value (honda) but I want blah blah to be sent

**Comment by hannalaakso** [comment]
Thanks for raising this @brendyhenry90. It looks like it's been reported previously with https://github.com/alphagov/accessible-autocomplete/issues/205 so I'm closing this issue.
