### ISSUE TITLE
Starting marking items with the arrow keys, overwrite any mouse selection

### ISSUE THREAD

**Issue by TiagoSusanoPinto** [alphagov/accessible-autocomplete#336]
If in the drop box, we go through the items using the keyboard arrow keys, and later we use the mouse to select an item, the selected item will be the one was marked when using the keyboard arrow keys (instead of the expected one that was selected with the mouse)

E.g.:
- Go to the the accessible-autocomplete example page (https://alphagov.github.io/accessible-autocomplete/examples/)
- Select the first "Select your country" field
- Press 'b'. It should show a list of countries, starting will Albania
- Press the down arrow key. It should mark Albania
- Use the mouse to select a different country (for example 'Bahamas')
- Albania appears in the end as the selected country

Might be slightly related with https://github.com/alphagov/accessible-autocomplete/issues/74

**Comment by vanitabarrett** [comment]
Hi @TiagoSusanoPinto, thank you for raising this issue. I'm not able to replicate the issue you're seeing any more, so I'm going to close the issue for now. Please re-open this if you believe this is still a problem with the latest version of the autocomplete.
