### ISSUE TITLE
User confusion over "Edit combo" announcement

### ISSUE THREAD

**Issue by kr8n3r** [alphagov/accessible-autocomplete#337]
Recording the issue raised by the user.

> I am using jaws, latest version. and Chrome also latest I think.
> windows 10 latest.
> 
> Jaws needs to be in a certain mode to type letters that will be picked up by online forms.
> 
> I can't make Jaws go into that mode without an edit box or combo box or some such thing to make it work.
> 
> So as I type the letters for Lewisham jaws thinks I amlooking for links, (L), edit boxes (E), and so on. My sighted help didn't see anything she could help with either.
> 
> I have a Jaws expert on the phone to me this afternoon so I'll see if he can sort it out and let you know.
> 
> It is not straightforward though and not helpful to screen reader users to go too fancy with stuff!! smile.
> 
> Thanks and I'll be in touch again.

Seems like the user was confused by the role="combobox" when on focus JAWS announces it with:

"Start typing and <label text>, **edit combo**.
To set a value use the arrow keys or type the value".

Before users start typing, arrow keys don't do anything.

**Comment by nickcolley** [comment]
Will be in the 2.0.0 release :)
