### ISSUE TITLE
Can't use more than one autocomplete on a page

### ISSUE THREAD

**Issue by benmarsh-hmrc** [alphagov/accessible-autocomplete#338]
When used more than once on a page, only the first autocomplete field behaves the way it was intended. Any autocomplete after the first doesn't display the drop down.

**Comment by 36degrees** [comment]
Thanks for raising this.

As far as I know, the accessible autocomplete _should_ support this. The [example page](https://alphagov.github.io/accessible-autocomplete/examples/) for example has a number of autocompletes working on the same page.

Are you able to share an example of the code you're using at the minute? That might help us understand what's going on.

**Comment by benmarsh-hmrc** [comment]
Realised it was an issue on our end but thank you for getting back so quickly.
