### ISSUE TITLE
Release new accessibility improvements 

### ISSUE THREAD

**Issue by nickcolley** [alphagov/accessible-autocomplete#358]
## What
Release the new accessibility improvement work

## Why
Our users can use a more accessible autocomplete to help them comply with the new regulations

## Depends on

- Write release notes for new accessibility improvements #357

## Done when

- [x] Component is released
- [x] Comms are sent to relevant channels

**Comment by hannalaakso** [comment]
Closed by https://github.com/alphagov/accessible-autocomplete/pull/376
