### ISSUE TITLE
Use aria-autocomplete?

### ISSUE THREAD

**Issue by tvararu** [alphagov/accessible-autocomplete#37]
I did some light testing previously where it seemed like this property was not being used by assistive technologies in any perceivable way, but there's a lingering question if we should add it anyway.

- https://www.w3.org/TR/wai-aria/states_and_properties#aria-autocomplete
- http://oaa-accessibility.org/example/10/
- http://ljwatson.github.io/design-patterns/autocomplete/index.html

**Comment by nickcolley** [comment]
Will be in the 2.0.0 release :)
