### ISSUE TITLE
VoiceOver on OSX 

### ISSUE THREAD

**Issue by accessiblewebuk** [alphagov/accessible-autocomplete#370]
Tested using Safari (don't know if it is the same for other browsers)

Typing in for example “UN” results in “11 Re un” - the word “results” is cut off. You can see the full text appear in the VoiceOver "11 results. United Kingdom 1 of ...", but it disappears in milliseconds.

**Comment by nickcolley** [comment]
There is new behaviour that waits a second or so before announcing these messages to resolve this issue in 2.0.0
