### ISSUE TITLE
VoiceOver - non-intuitive behaviour to get to list of results

### ISSUE THREAD

**Issue by accessiblewebuk** [alphagov/accessible-autocomplete#372]
After typing in the on screen keyboard, the user has to either dismiss it or move touch to the top area of the screen to get to results. This doesn't feel intuitive, user testing can indicate if users manage to work this out, but it may help to have some guidance instructions available (preferably only available to VoiceOver screen reader users)

**Comment by nickcolley** [comment]
The 2.0.0 release includes guidance for how to interact with the component
