### ISSUE TITLE
NVDA with Firefox and Internet Explorer - reads out confusing numbers when scrolling

### ISSUE THREAD

**Issue by accessiblewebuk** [alphagov/accessible-autocomplete#374]
NVDA Initially reads out “1 of x” for each item, but then changes to “2 of x” and so on - this is confusing. It may be that it is indicating that it is an instance of the list  (1 of x) and then the sequence in the list (2 of x) but the first part isn't helpful.

**Comment by nickcolley** [comment]
Resolved in 2.0.0 :)
