### ISSUE TITLE
Throttle requests documenation

### ISSUE THREAD

**Issue by imranazad** [alphagov/accessible-autocomplete#380]
I can't seem to find any documentation on how to throttle remote requests. In it's current state the typeahead sends a request on every single key press. Is the lack of documentation due to there being no throttling?

Can anyone please advise? @nickcolley 

Thanks

**Comment by nickcolley** [comment]
Heya,

We're talking about how to do this over in this thread so hopefully my comment helps you with this:

https://github.com/alphagov/accessible-autocomplete/issues/210#issuecomment-549470423

Feel free to add to that thread if it does not.

**Comment by imranazad** [comment]
Hey @nickcolley Thanks appreciate that. We managed to implement throttling ourselves.
