### ISSUE TITLE
showNoOptionsFound: false not working in demo?

### ISSUE THREAD

**Issue by jrochkind** [alphagov/accessible-autocomplete#389]
In the demo page at https://alphagov.github.io/accessible-autocomplete/examples/, there is an example that says

`{ showNoOptionsFound: false }`: "This option will toggle displaying the "No results found" message."

However, entering text like `nosuchoption` in the input field in that box... I don't see a "No results found" message of any kind, in either Chrome or Firefox.

**Comment by nickcolley** [comment]
Hello @jrochkind,

When `showNoOptionsFound` is set to `false` then it will not show a 'No results found' message, so I think this example is working as intended.

Does this align with what you were thinking should happen? I wonder if we could improve the wording.

**Comment by jrochkind** [comment]
Aha, I got confused about what the default was and what the non-default was, and what that example was demo'ing!  I see it now, thanks for the quick response, sorry for the false alarm. 

This is a very nice tool, seems to have just the right amount of features.
