### ISSUE TITLE
 Add a waiting message for async loading

### ISSUE THREAD

**Issue by mblanloeil** [alphagov/accessible-autocomplete#391]
Hi
How can we add a mesasge in the dropdown to warn the user that the results are being loaded? Currently "No Result Found" is displayed when the query leaves, not when it returns.

Thanks

**Comment by nickcolley** [comment]
Heya @mblanloeil,

There's a relevant discussion over at https://github.com/alphagov/accessible-autocomplete/issues/210 around this.

On the Design System website we override the 'no results' message depending on if data has been loaded yet, you can see an example of this here:

https://github.com/alphagov/govuk-design-system/blob/b52f17e5db38feb0f9b0b1412df9649c9335a84e/src/javascripts/components/search.js#L37

If you search for the instances of `statusMessage` you can see when it gets updated.

**Comment by mblanloeil** [comment]
Thank's !! It's ok !
