### ISSUE TITLE
Issue with selecting items from dropdown

### ISSUE THREAD

**Issue by martinlex** [alphagov/accessible-autocomplete#408]
We have a kind of special situation:
My colleague can fail to select an item from the list, whereas I cannot.
When she clicks, it behaves like pressing "ESC", meaning: the item is not selected, it just keeps whatever you wrote, and closes the dropdown.
I, on the other hand, cannot recreate this bug. We have tried with Mac (both clickpad and mouse) and Dell laptop (both clickpad and mouse).
It seems to me, when I click very gently and very softly, I can recreate it (sometimes).
It sounds so silly, I know 😂😂
Is there a known problem with "light/short clicking" and "hard/long clicking"??? 
Don't know where to go from here, please help.

**Comment by nickcolley** [comment]
I think this might be related to : https://github.com/alphagov/accessible-autocomplete/issues/328

**Comment by martinlex** [comment]
Oh, thanks! So we were not alone! It looks like the pull request for this fix has merge conflicts. Will this fix be approved and merged later on?

**Comment by nickcolley** [comment]
@martinlex I've asked the team about this, we didnt plan on fixing this bug as we don't have much time right now.

That pull request may or may not fix this issue so we'd need to do more work.

If I don't get back to you sooner I've put 'awaiting-triage' on this card which we use to keep track of cards we need to talk about as a team.

Thanks for your patience.

**Comment by martinlex** [comment]
@nickcolley 
Thanks Nick. Meanwhile, is there a fix I can apply locally? We are loading from npm module.

**Comment by nickcolley** [comment]
@martinlex I'm not aware of a quick easy fix since I don't understand why this problem is happening, sorry I can't be more helpful sorry Martin!

**Comment by martinlex** [comment]
I understand. The PR #342 adds a mouseDown event
`onMouseDown={(event) => this.handleOptionClick(event, index)}`
Have you tried to see if that is the solution?
Thank you for the feedback 👍

**Comment by nickcolley** [comment]
I'll have a poke around to see what I can learn and let you know if there's anything helpful short term/ long term.
