### ISSUE TITLE
Tests are failing on the master branch

### ISSUE THREAD

**Issue by 36degrees** [alphagov/accessible-autocomplete#435]
The tests are currently failing on the master branch.

The same commit that [passed on April 15](https://travis-ci.com/github/alphagov/accessible-autocomplete/builds/160362005) is now [failing](https://travis-ci.com/github/alphagov/accessible-autocomplete/builds/171596994) with:

```
ERROR: connect ECONNREFUSED 127.0.0.1:4445
firefox.55_0.windows10
    at new RuntimeError (/home/travis/build/alphagov/accessible-autocomplete/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/home/travis/build/alphagov/accessible-autocomplete/node_modules/webdriverio/build/lib/utils/RequestHandler.js:330:43)
    at self.callback (/home/travis/build/alphagov/accessible-autocomplete/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.onRequestError (/home/travis/build/alphagov/accessible-autocomplete/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:187:15)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

We believe this is because Travis has updated to Sauce Connect Proxy v4.6.2, although this is based off [second hand information found whilst searching GitHub](https://github.com/catmaid/CATMAID/commit/6dd19a1d0a285afe3dea6fe108ac9bb72c5b4836).

Sauce Connect Proxy v4.6.1 [disables Selenium Relay by default](https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy+Change+Logs). Selenium Relay appears to be deprecated with intent to remove it entirely in the future [2]. You can enable it by setting `--se-port`, but there doesn’t seem to be a way to configure Travis’ saucelabs ‘addon’ to do this.

Our tests seem to rely on Selenium Relay in order to create the tunnel so that SauceLabs can access the server running on localhost in Travis. We’re using wdio-sauce-service v0.4.13 which relies on Selenium Relay to work (it’s [hardcoded to connect to localhost:4445](https://github.com/webdriverio-boneyard/wdio-sauce-service/blob/14f49591080552b9e93ce48155560208bfd7ec14/lib/sauce-launch-service.js#L18-L19 ) which we believe is where Selenium Relay should be listening). The latest version is [v6.1.16](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-sauce-service), which [no longer seems to rely on Selenium Relay](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-sauce-service/src/launcher.js#L42-L52).

Neither Travis nor SauceLabs appear to have really communicated this change (which was made in a patch release of SauceLabs Connect Proxy) nor made it clear what the expected migration path is.

## Options

- Try updating to the latest version of webdriver / wdio-sauce-service, and see if that fixes it
- Try and pin to using an older version of Sauce Connect Proxy, or otherwise configure Travis to enable Selenium Relay by setting `--se-port`
- Remove the SauceLabs integration and rely on running Selenium standalone with headless Chrome?
- ???

**Comment by lfdebrux** [comment]
This might be a Travis problem, the Travis config has a warning `root: duplicate key: addons` and the resultant build config doesn't have any reference to `sauce_connect`

https://travis-ci.com/github/alphagov/accessible-autocomplete/jobs/349701035/config

**Comment by 36degrees** [comment]
So, we are now seeing 'Starting Sauce Connect' in the build output, which suggests the duplicate keys was an issue, but the tests still fail with the same error and, notably, the previous passing build (https://travis-ci.com/github/alphagov/accessible-autocomplete/builds/160362005) did not include 'Starting Sauce Connect' in the test output.

This suggests that the tests perhaps aren't actually reliant on the `sauce_connect` Travis addon? In which case, I'm struggling to understand what's changed that means the tests no longer pass.

**Comment by 36degrees** [comment]
It looks like `wdio-sauce-service` includes [`sauce-connect-launcher`](https://github.com/bermi/sauce-connect-launcher) which installs the latest version of Sauce Connect Proxy by default.

v4.6.1 came out in May, so that explains why the tests passed in April.

I think we might be able to fix this by pinning the version using `SAUCE_CONNECT_VERSION` as described here: https://github.com/bermi/sauce-connect-launcher#sauce-connect-version

I think we might also want to remove the sauce_connect addon from `travis.yml` as as far as I can tell the tests don't rely on it, as wdio-sauce-service installs and sets up Sauce Connect Proxy anyway.
