### ISSUE TITLE
How to provide distinct values and labels?

### ISSUE THREAD

**Issue by n1k0** [alphagov/accessible-autocomplete#478]
Hello, I retrieve autocomplete data from a remote endpoint and populate results using `populateResults`:

```js
    accessibleAutocomplete({
      element: el,
      id: "search_where",
      name: "where",
      source: debounce(async (query, populateResults) => {
        const res = await fetch(`${url}?q=${encodeURIComponent(query)}`);
        const data = await res.json();
        populateResults(res.results);
      }, 100),
    });
```

The `res.results` list received is of this form:

```js
{
    "q": "pari",
    "results": [
        {
            "id": "75",
            "text": "Paris (département 75)"
        },
        {
            "id": "75056",
            "text": "Paris (75)"
        },
        // […]
    ]
}
```

I would like to render the `text` property value as the option label, but retrieve the `id` value when an option is selected by the user (a bit like what is possible using a regular `<select>` and `<option value="42">Answer</option>`). What data structure should I pass to `populateResults` to achieve that, if that's even possible?

 Thanks for your help!

**Comment by edwardhorsford** [comment]
@n1k0 we did something this week that might be helpful for you - [pr here](https://github.com/DFE-Digital/register-trainee-teachers-prototype/pull/224).

Essentially we create a hidden input to store the id of the selected item - and then use that on the server to look up the thing. It looks like we're using the `onConfirm` option to all our own function that sets the relevant thing.

Note of course this relies on js so if you're using progressive enhancement you'll probably want a server-side solution too.

**Comment by n1k0** [comment]
@edwardhorsford the hidden input is definitely a clever trick! I feel that distinguishing values and labels might still look like something we'd want natively though :) I feel like accepting a list of `{ value, label }` alternatively to just labels may be relatively easy to implement while staying perfectly backward-compatible, but I may be wrong here. Would be nice to hear from maintainers about that though!

**Comment by edwardhorsford** [comment]
@n1k0 I agree it would be good to include, but I don't think you'll see it happen sadly - I wouldn't consider this repo actively maintained. It gets security fixes, but I don't think is a priority for GDS so hasn't had much in the way of feature work done on it for some years.

**Comment by n1k0** [comment]
@edwardhorsford I was just browsing issues, PR and commit history… I understand. Too bad as there aren't many accessible autocomplete libraries out there 😢

**Comment by faithandrel** [comment]
My solution in React:
```javascript
  const find = (key, array) => {
    return array.filter(item => item.text.toLowerCase().indexOf(key) !== -1);
  }

  const source = (query, populateResults) => {
    const cities = [
      {id: 1, text: 'Paris'},
      {id: 2, text: 'London'},
      {id: 3, text: 'Berlin'},
      {id: 4, text: 'Vienna'},
    ];
    const results = find(query, cities);
    populateResults(results);
  }

  const templates = {
    inputValue: (value) => {
      if (!value) {
        return '';
      }
      return value.text;
    },
    suggestion: (value) => {
      return value.text;
    }
  }

  const onConfirm = (selected) => {
    setSelected(selected.id)
  };
```

```jsx
<Autocomplete id='autocomplete'
                      source={source}
                      templates={templates}
                      onConfirm={onConfirm}
                      confirmOnBlur={false} />
```

**Comment by n1k0** [comment]
@faithandrel ah, using `templates` is the way to go indeed, totally missed that reading the docs. Thank you for the hint, that's nicely solving my problem 👍
