### ISSUE TITLE
Multi select feature?

### ISSUE THREAD

**Issue by mmokross** [alphagov/accessible-autocomplete#480]
If I need to be able to select multipe items from the existing list, is this component the right one to choose? If so, what is the best way to achieve this?
(A mix with #479 would be cool ;)

**Comment by edwardhorsford** [comment]
This component isn't really set up for that - you'd be better off using a 'add another'  pattern to reveal a second autocomplete.

With all that said, you *might* be able to hack it in with your own source function doing more complex matching - it could probably be made to work with comma separated strings. But I'd be concerned about the accessibility of this - you'd definitely want to test heavily with AT as it's rather outside the ambition of this project.

**Comment by mmokross** [comment]
Thank you for the honest answer. I had already feared this, but hope dies last ;-)
