### ISSUE TITLE
Use Preact only as a production optimization

### ISSUE THREAD

**Issue by nickcolley** [alphagov/accessible-autocomplete#54]
Right now the tests are a bit hairy compared with what can be done in the React world, spoke to @tvararu and we think it'd be interesting to have this project as React by default, and then allow Preact to be swapped in at prod build time.

Risks with this is we need to ensure test coverage across a React build and Preact build...

**Comment by tvararu** [comment]
(Leaving note here so I can remove from bookmarks) @nickcolley pointed out that we could use [something like this factory loader](https://gist.github.com/developit/63466862f1aa808b1438ca86019eb9bd) for this.

**Comment by nickcolley** [comment]
This seems like a nice to have to me.
