### ISSUE TITLE
onConfirm returns the option, not the value

### ISSUE THREAD

**Issue by chrisrhymes** [alphagov/accessible-autocomplete#563]
I am using the progressive enhancement option to convert a select into an autocomplete. 

In the example below, the value is "fr", "de" or "gb" in the option tags, but onConfirm only returns the string "France", "Germany" or "United Kingdom" and not the value? Is there a way to get the value selected? 

```html
<select id="location-picker">
  <option value="fr">France</option>
  <option value="de">Germany</option>
  <option value="gb">United Kingdom</option>
</select>
```

```javascript
accessibleAutocomplete.enhanceSelectElement({
        defaultValue: '',
        selectElement: document.querySelector('#location-picker'),
        confirmOnBlur: false,
        onConfirm: (option) => {
            console.log(option);
        }
});
```

**Comment by chrisrhymes** [comment]
Just seen this is a duplicate of #387

**Comment by joelanman** [comment]
closing as a duplicate, @chrisrhymes if thats ok, feel free to reopen if not
