### ISSUE TITLE
Add support for "required" attribute

### ISSUE THREAD

**Issue by tvararu** [alphagov/accessible-autocomplete#59]
Make it possible to pass an argument to the `AccessibleTypeahead` function to set the [`required` attribute](https://www.wufoo.com/html5/attributes/09-required.html) on the typeahead input field. This is useful if the need involves free text submission.

**Comment by samtsai** [comment]
@tvararu Good to close this?

**Comment by tvararu** [comment]
@samtsai yes! Forgot. 🌈
