### ISSUE TITLE
React component - Invalid ARIA attribute value: aria-activedescendant="false"

### ISSUE THREAD

**Issue by jamesmking** [alphagov/accessible-autocomplete#596]
We're using the React component from version 2.0.4. Our accessibility tests are flagging an invalid ARIA attribute value: `aria-activedescendant="false"` on the combobox. The value should represent an ID of the currently focused element.

The issue can be replicated using the React example page, and running aXe Devtools:
https://alphagov.github.io/accessible-autocomplete/examples/react/

**Comment by kuljitsingh4444** [comment]
Any updates on this issue, seems like a critical issue ?
