### ISSUE TITLE
Release new version of accessible autocomplete

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/accessible-autocomplete#669]
## What

Release a new version of the accessible autocomplete

## Why

To publish the recent changes to the accessible autocomplete

## Who needs to work on this

Developers, Technical writers

## Who needs to review this

Developers, Technical writers

## Done when

- [ ] A new release has been published

**Comment by romaricpascal** [comment]
Blocked until we complete the other issues in [the 'next' Milestone](https://github.com/alphagov/accessible-autocomplete/milestone/7).

**Comment by querkmachine** [comment]
We released Accessible Autocomplete 3.0 on Friday, so I'm going to say this has been done. 🚀
