### ISSUE TITLE
Unicode support?

### ISSUE THREAD

**Issue by tvararu** [alphagov/accessible-autocomplete#78]
There aren't any tests that check unicode strings, so we don't know if the autocomplete works with them.

**Comment by edwardhorsford** [comment]
Possibly related: ideally the picker should be agnostic to whether users enter with diacrytic characters or not.

Test case: user enters Hayastán or Hayastan. Both should return with Armenia.

**Comment by tvararu** [comment]
Going to assume this works until someone files a bug, closing. :)
